# **PANDAS**

##DataFrame

it is the key data structure in pandas.it allows us to store and manipulate tabular data as a 2D data structures.


Different ways to create dataframe


1.   Through reading csv file
2.   Through reading excel file

1.   Through python dictionary
2.   Through python tuple list

1.  Through python dictionary

Create a simple Pandas DataFrame:

In [ ]:
import pandas as pd
data={'calories':[389,420,440],
      'duration':[50,40,45]}
df=pd.DataFrame(data)
df

   calories  duration
0       389        50
1       420        40
2       440        45

###Create dataframe using Python dictionary

In [ ]:
import pandas as pd
emp={'id':[101,102,103,104,105],
     'name':['deepak','shyam','arun','manu','jeena'],
     'age':[25,22,24,20,27],
     'salary':[25000,30000,150000,10000,300000]}
df=pd.DataFrame(emp)
df

    id    name  age  salary
0  101  deepak   25   25000
1  102   shyam   22   30000
2  103    arun   24  150000
3  104    manu   20   10000
4  105   jeena   27  300000

###Create datafrme using python tuple list

In [ ]:
import pandas as pd
empty_data=[(101,'deepak',25,25000),
            (102,'shyam',22,30000),
            (103,'arun',24,150000),
            (104,'manu',20,10000),
            (105,'jeena',27,30000)]
df=pd.DataFrame(empty_data,columns=['id','name','age','salary'])
df

    id    name  age  salary
0  101  deepak   25   25000
1  102   shyam   22   30000
2  103    arun   24  150000
3  104    manu   20   10000
4  105   jeena   27   30000

###Create Dataframe using a list of dictionaries

In [ ]:
import pandas as pd
emp_data_list=[{'id':101,'name':'deepak','age':25,'salary':25000},
               {'id':102,'name':'shyam','age':22,'salary':30000},
               {'id':103,'name':'arun','age':24,'salary':150000},
               {'id':104,'name':'manu','age':20,'salary':10000},
               {'id':105,'name':'jeena','age':27,'salary':30000}]
df=pd.DataFrame(emp_data_list)
df

    id    name  age  salary
0  101  deepak   25   25000
1  102   shyam   22   30000
2  103    arun   24  150000
3  104    manu   20   10000
4  105   jeena   27   30000

##Pandas Series

A pandas series like a column in a table

it is one-dimensional array holding data of any type.

Create a simple Pandas Series from a list:

In [ ]:
import pandas as pd

a=[1,7,2]
myvar=pd.Series(a)
print(myvar)

0    1
1    7
2    2
dtype: int64

##Labels

If nothing  else is specified,the values are labeled with their index number.First value has index 0,second value has index 1 etc.

In [ ]:
import pandas as pd
a=[1,7,2]
myvar=pd.Series(a)
print(myvar)
print(myvar[0])

0    1
1    7
2    2
dtype: int64
1

In [ ]:
import pandas as pd
a=[1,7,2]
myvar=pd.Series(a,index=['x','y','z'])
print(myvar)
print(myvar['y'])

x    1
y    7
z    2
dtype: int64
7

###Key Value Objects as series

In [ ]:
import pandas as pd
calories={'day1':420,'day2':300,'day3':390}
myvar=pd.Series(calories)
print(myvar)

day1    420
day2    300
day3    390
dtype: int64

In [ ]:
import pandas as pd
calories={'day1':420,'day2':300,'day3':390}
myvar=pd.Series(calories,index=['day1','day2'])
print(myvar)

day1    420
day2    300
dtype: int64

##Read txt file

In [ ]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dataset/data.csv')
print(df)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

##Read excel file

In [ ]:
import pandas as pd
df=pd.read_excel('/content/drive/MyDrive/Colab Notebooks/dataset/employee_sample.xlsx')
print(df)

   ID     NAME DEPARTMENT
0   1    Alice         HR
1   2      Bob    Finance
2   3  Charlie         IT

##Skip the unnecessary header or add yours

In [ ]:
import pandas as pd
data=pd.read_excel('/content/drive/MyDrive/Colab Notebooks/dataset/employee_salary_data.xlsx',skiprows=1)
print(data)

   101    Alice         HR  50000
0  102      Bob    Finance  60000
1  103  Charlie         IT  70000
2  104    David  Marketing  55000
3  105      Eva         IT  72000

**Pandas - Cleaning Data**

Data set:-

In [ ]:
import pandas as pd
data=pd.read_excel('/content/drive/MyDrive/Colab Notebooks/dataset/workout_data.xlsx')
print(data)

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112       NaN
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         NaN    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132       NaN
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

->**Empty Cells**

Empty cells can potentially give you a wrong result when you analyze data.

Remove Rows:-

The result from the converting in the example above gave us a NaT value, which can be handled as a NULL value, and we can remove the row by using the dropna() method.

eg :-Return a new Data Frame with no empty cell

In [ ]:
import pandas as pd
df=pd.read_excel('/content/drive/MyDrive/Colab Notebooks/dataset/workout_data.xlsx')
new_df=df.dropna()
print(new_df.to_string())

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

 the dropna() method returns a new DataFrame, and will not change the original.

If you want to change the original DataFrame, use the inplace = True argument:

eg :-Remove all rows with NULL values:

In [ ]:
import pandas as pd
df=pd.read_excel('/content/drive/MyDrive/Colab Notebooks/dataset/workout_data.xlsx')
df.dropna(inplace=True)
print(df.to_string)

<bound method DataFrame.to_string of     Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0>

the dropna(inplace = True) will NOT return a new DataFrame, but it will remove all rows containing NULL values from the original DataFrame.

**Replace Empty Values**

Another way of dealing with empty cells is to insert a new value instead.


This way you do not have to delete entire rows just because of some empty cells.


The fillna() method allows us to replace empty cells with a value:

 eg:-Replace NULL values with the number 130:

In [ ]:
import pandas as pd
df=pd.read_excel('/content/drive/MyDrive/Colab Notebooks/dataset/workout_data.xlsx')
df.fillna(130,inplace=True)
print(df.to_string())

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112     130.0
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         130    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132     130.0
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

**Replace Only For Specified Columns**

The example above replaces all empty cells in the whole Data Frame.


To only replace empty values for one column, specify the column name for the DataFrame:

eg:-Replace NULL values in the "Calories" columns with the number 130:

In [ ]:
import pandas as pd
df=pd.read_excel('/content/drive/MyDrive/Colab Notebooks/dataset/workout_data.xlsx')
df.fillna({'Calories':130},inplace=True)
print(df.to_string())

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112     130.0
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         NaN    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132     130.0
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

**Replace Using Mean, Median, or Mode**

A common way to replace empty cells, is to calculate the mean, median or mode value of the column.


Pandas uses the mean() median() and mode() methods to calculate the respective values for a specified column:

EG:-Calculate the MEAN, and replace any empty values with it:

eg:-Calculate the MEAN, and replace any empty values with it:

In [ ]:
import pandas as pd
df=pd.read_excel('/content/drive/MyDrive/Colab Notebooks/dataset/workout_data.xlsx')
x=df['Calories'].mean()
df.fillna({'Calories':x},inplace=True)
print(df.to_string())

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130    409.10
1         60  2020/12/02    117       145    479.00
2         60  2020/12/03    103       135    340.00
3         45  2020/12/04    109       175    282.40
4         45  2020/12/05    117       148    406.00
5         60  2020/12/06    102       127    300.00
6         60  2020/12/07    110       136    374.00
7        450  2020/12/08    104       134    253.30
8         30  2020/12/09    109       133    195.10
9         60  2020/12/10     98       124    269.00
10        60  2020/12/11    103       147    329.30
11        60  2020/12/12    100       120    250.70
12        60  2020/12/12    100       120    250.70
13        60  2020/12/13    106       128    345.30
14        60  2020/12/14    104       132    379.30
15        60  2020/12/15     98       123    275.00
16        60  2020/12/16     98       120    215.20
17        60  2020/12/17    100       120    300.00
18        45  2020/12/18     90       112    304.68
19        60  2020/12/19    103       123    323.00
20        45  2020/12/20     97       125    243.00
21        60  2020/12/21    108       131    364.20
22        45         NaN    100       119    282.00
23        60  2020/12/23    130       101    300.00
24        45  2020/12/24    105       132    246.00
25        60  2020/12/25    102       126    334.50
26        60  2020/12/26    100       120    250.00
27        60  2020/12/27     92       118    241.00
28        60  2020/12/28    103       132    304.68
29        60  2020/12/29    100       132    280.00
30        60  2020/12/30    102       129    380.30
31        60  2020/12/31     92       115    243.00

eg:-Calculate the MEDIAN, and replace any empty values with it:

In [ ]:
import pandas as pd
df=pd.read_excel('/content/drive/MyDrive/Colab Notebooks/dataset/workout_data.xlsx')
x=df['Calories'].median()
df.fillna({'Calories':x},inplace=True)
print(df.to_string())

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112     291.2
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         NaN    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132     291.2
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

eg:-Calculate the MODE, and replace any empty values with it:

In [ ]:
import pandas as pd
df=pd.read_excel('/content/drive/MyDrive/Colab Notebooks/dataset/workout_data.xlsx')
x=df['Calories'].mode()[0]
df.fillna({'Calories':x},inplace=True)
print(df.to_string())

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112     300.0
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         NaN    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132     300.0
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

**Convert Into a Correct Format**

In [ ]:
import pandas as pd
df=pd.read_excel('/content/drive/MyDrive/Colab Notebooks/dataset/workout_sample.xlsx')
print(df)

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112       NaN
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         NaN    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132       NaN
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

Check out row 22 and 26, the 'Date' column should be a string that represents a date:

to convert all cells in the 'Date' column into dates.

Pandas has a to_datetime() method for this:

eg;-Convert to date:

In [ ]:
import pandas as pd
df=pd.read_excel('/content/drive/MyDrive/Colab Notebooks/dataset/workout_data.xlsx')
df['Date']=pd.to_datetime(df['Date'],format='mixed')
print(df.to_string())

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
22        45        NaT    100       119     282.0
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

the empty date in row 22 got a NaT (Not a Time) value, in other words an empty value. One way to deal with empty values is simply removing the entire row.

 so,remove rows with a NULL value in the "Date" column:

In [ ]:
df.dropna(subset=['Date'],inplace=True)
print(df.to_string())

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112       NaN
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132       NaN
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

**Pandas - Fixing Wrong Data**

---

**Wrong Data**

"Wrong data" does not have to be "empty cells" or "wrong format", it can just be wrong, like if someone registered "199" instead of "1.99".

If you take a look at our data set, you can see that in row 7, the duration is 450, but for all the other rows the duration is between 30 and 60.

One way to fix wrong values is to replace them with something else.

In our example, it is most likely a typo, and the value should be "45" instead of "450", and we could just insert "45" in row 7:

In [ ]:
import pandas as pd
df=pd.read_excel('/content/drive/MyDrive/Colab Notebooks/dataset/workout_sample.xlsx')
df.loc[7,'Duration']=45
print(df.to_string())

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7         45  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112       NaN
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         NaN    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132       NaN
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

In [ ]:
df.dropna(inplace=True)
print(df.to_string())

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7         45  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

For small data sets you might be able to replace the wrong data one by one, but not for big data sets.

To replace wrong data for larger data sets you can create some rules, e.g. set some boundaries for legal values, and replace any values that are outside of the boundaries.

eg:-Loop through all values in the "Duration" column.

If the value is higher than 120, set it to 120:

In [ ]:
for x in df.index:
  if df.loc[x,'Duration']>120:
    df.loc[x,'Duration']=120

Another way of handling wrong data is to remove the rows that contains wrong data.

eg :Delete rows where "Duration" is higher than 120

In [ ]:
for x in df.index:
  if df.loc[x,"Duration"]>120:
    df.drop(x,inplace=True)

**Pandas - Removing
Duplicates**

---


**Discovering Duplicates**

Duplicate rows are rows that have been registered more than one time.

By taking a look at our test data set, we can assume that row 11 and 12 are duplicates.

To discover duplicates, we can use the duplicated() method.

The duplicated() method returns a Boolean values for each row:

 eg:Returns True for every row that is a duplicate, otherwise False:

In [ ]:
print(df.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
19    False
20    False
21    False
23    False
24    False
25    False
26    False
27    False
29    False
30    False
31    False
dtype: bool

To remove duplicates, use the drop_duplicates() method.

In [ ]:
df.drop_duplicates(inplace=True)
print(df.to_string())

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7         45  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

The (inplace = True) will make sure that the method does NOT return a new DataFrame, but it will remove all duplicates from the original DataFrame.

##Using Converters

Using converters to convert data using conditions

In [ ]:
#convert occupation of doctor to teacher
def convert(occupation):
  if occupation=='doctor':
    return 'teacher'
  else:
    return occupation

data=pd.read_excel('/content/drive/MyDrive/Colab Notebooks/dataset/sample_data_doctor.xlsx',converters={'occupation':convert})
print(data)

    name                age occupation
0   john                 23   Engineer
1  alice                 30    teacher
2   ammu  not available age    teacher

##Write to excel

use to_excel()

In [ ]:
data.to_excel('occupation.xlsx')

In [ ]:
data

    name                age occupation
0   john                 23   Engineer
1  alice                 30    teacher
2   ammu  not available age    teacher

###Write two data frames in a single excel file

to write two data frames in a single excel file use ExcelWriter() method

In [ ]:
import pandas as pd

# Example DataFrames
data1=pd.DataFrame({'Name':['john','alice'],
                    'age':[23,30]})
data2=pd.DataFrame({'product':['pen','notebook'],
                    'price':[10,50]})

with pd.ExcelWriter('new file 1.xlsx')as wr:
  data1.to_excel(wr,sheet_name='sheet1')
  data2.to_excel(wr,sheet_name='sheet2')

In [ ]:
data1

    Name  age
0   john   23
1  alice   30

In [ ]:
data2

    product  price
0       pen     10
1  notebook     50

In [ ]:
import pandas as pd
data=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dataset/airlines_flights_data.csv')
data

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [ ]:
data.head()

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [ ]:
data.head(3)

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956

In [ ]:
data.tail()

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [ ]:
data.tail(3)

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [ ]:
data.shape

(300153, 12)

In [ ]:
data.info()#to print details about the data,to find null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   index             300153 non-null  int64
 1   airline           300153 non-null  object
 2   flight            300153 non-null  object
 3   source_city       300153 non-null  object
 4   departure_time    300153 non-null  object
 5   stops             300153 non-null  object
 6   arrival_time      300153 non-null  object
 7   destination_city  300153 non-null  object
 8   class             300153 non-null  object
 9   duration          300153 non-null  float64
 10  days_left         300153 non-null  int64
 11  price             300153 non-null  int64
dtypes: float64(1), int64(3), object(8)
memory usage: 27.5+ MB

In [ ]:
data.describe() #print all statistical results

               index       duration      days_left          price
count  300153.000000  300153.000000  300153.000000  300153.000000
mean   150076.000000      12.221021      26.004751   20889.660523
std     86646.852011       7.191997      13.561004   22697.767366
min         0.000000       0.830000       1.000000    1105.000000
25%     75038.000000       6.830000      15.000000    4783.000000
50%    150076.000000      11.250000      26.000000    7425.000000
75%    225114.000000      16.170000      38.000000   42521.000000
max    300152.000000      49.830000      49.000000  123071.000000

In [ ]:
data[['airline','price']]  #to selsect multiple column( 2 dimension table)

         airline  price
0       SpiceJet   5953
1       SpiceJet   5953
2        AirAsia   5956
3        Vistara   5955
4        Vistara   5955
...          ...    ...
300148   Vistara  69265
300149   Vistara  77105
300150   Vistara  79099
300151   Vistara  81585
300152   Vistara  81585

[300153 rows x 2 columns]

In [ ]:
data[5:20]

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
5,5,Vistara,UK-945,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.33,1,5955
6,6,Vistara,UK-927,Delhi,Morning,zero,Morning,Mumbai,Economy,2.08,1,6060
7,7,Vistara,UK-951,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.17,1,6060
8,8,GO_FIRST,G8-334,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.17,1,5954
9,9,GO_FIRST,G8-336,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.25,1,5954
10,10,GO_FIRST,G8-392,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.25,1,5954
11,11,GO_FIRST,G8-338,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.33,1,5954
12,12,Indigo,6E-5001,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.17,1,5955
13,13,Indigo,6E-6202,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.17,1,5955
14,14,Indigo,6E-549,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.25,1,5955
15,15,Indigo,6E-6278,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
16,16,Air_India,AI-887,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.08,1,5955
17,17,Air_India,AI-665,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.17,1,5955
18,18,AirAsia,I5-747,Delhi,Evening,one,Early_Morning,Mumbai,Economy,12.25,1,5949
19,19,AirAsia,I5-747,Delhi,Evening,one,Morning,Mumbai,Economy,16.33,1,5949

In [ ]:
data[5:100:4]

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
5,5,Vistara,UK-945,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.33,1,5955
9,9,GO_FIRST,G8-336,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.25,1,5954
13,13,Indigo,6E-6202,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.17,1,5955
17,17,Air_India,AI-665,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.17,1,5955
21,21,GO_FIRST,G8-101,Delhi,Early_Morning,one,Night,Mumbai,Economy,14.50,1,5954
25,25,Vistara,UK-933,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.17,1,6690
29,29,Indigo,6E-5041,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,10470
33,33,Vistara,UK-817,Delhi,Evening,one,Morning,Mumbai,Economy,16.17,1,12150
37,37,Air_India,AI-453,Delhi,Early_Morning,one,Afternoon,Mumbai,Economy,8.83,1,11900
41,41,Air_India,AI-502,Delhi,Afternoon,one,Morning,Mumbai,Economy,19.08,1,12150
45,45,SpiceJet,SG-339,Delhi,Evening,one,Afternoon,Mumbai,Economy,19.58,1,12230
49,49,Air_India,AI-9643,Delhi,Evening,one,Afternoon,Mumbai,Economy,20.83,1,12938
53,53,Air_India,AI-9645,Delhi,Afternoon,one,Afternoon,Mumbai,Economy,21.75,1,13086
57,57,Indigo,6E-2193,Delhi,Afternoon,one,Night,Mumbai,Economy,8.33,1,13279
61,61,Vistara,UK-747,Delhi,Early_Morning,one,Afternoon,Mumbai,Economy,6.50,1,13935
65,65,Vistara,UK-817,Delhi,Evening,one,Night,Mumbai,Economy,28.17,1,14093
69,69,Vistara,UK-871,Delhi,Night,one,Afternoon,Mumbai,Economy,17.92,1,14408
73,73,Vistara,UK-747,Delhi,Early_Morning,one,Night,Mumbai,Economy,13.83,1,14985
77,77,Vistara,UK-809,Delhi,Evening,one,Night,Mumbai,Economy,24.42,1,15983
81,81,Indigo,6E-2102,Delhi,Early_Morning,one,Afternoon,Mumbai,Economy,5.08,1,15720
85,85,Vistara,UK-835,Delhi,Evening,one,Night,Mumbai,Economy,26.67,1,16665
89,89,Vistara,UK-819,Delhi,Afternoon,one,Night,Mumbai,Economy,7.58,1,17348
93,93,Vistara,UK-705,Delhi,Early_Morning,one,Afternoon,Mumbai,Economy,5.50,1,17400
97,97,Vistara,UK-673,Delhi,Afternoon,one,Evening,Mumbai,Economy,5.00,1,17663

In [ ]:
data['price'].mean()

np.float64(20889.660523133203)

In [ ]:
data[(data['price']>10000) & (data['price']<20000)]

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
28,28,SpiceJet,SG-8169,Delhi,Evening,zero,Night,Mumbai,Economy,2.33,1,10260
29,29,Indigo,6E-5041,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,10470
30,30,GO_FIRST,G8-165,Delhi,Early_Morning,one,Afternoon,Mumbai,Economy,8.00,1,10575
31,31,Indigo,6E-2373,Delhi,Afternoon,one,Evening,Mumbai,Economy,6.00,1,10838
32,32,Vistara,UK-813,Delhi,Evening,one,Morning,Mumbai,Economy,14.67,1,12150
...,...,...,...,...,...,...,...,...,...,...,...,...
299945,299945,Air_India,AI-545,Chennai,Evening,zero,Night,Hyderabad,Business,1.42,45,15000
299987,299987,Air_India,AI-545,Chennai,Evening,zero,Night,Hyderabad,Business,1.42,46,15000
300029,300029,Air_India,AI-545,Chennai,Evening,zero,Night,Hyderabad,Business,1.42,47,15000
300069,300069,Air_India,AI-545,Chennai,Night,zero,Night,Hyderabad,Business,1.33,48,15000
300111,300111,Air_India,AI-545,Chennai,Evening,zero,Night,Hyderabad,Business,1.42,49,15000

In [ ]:
data.set_index(data['index'])

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
index,,,,,,,,,,,,
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

**Loading data set**

In [ ]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dataset/airlines_flights_data.csv')
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

##Group by

to get list of group by airlines

In [ ]:
group_result=df.groupby('airline')
list(group_result)

[('AirAsia',
           index  airline   flight source_city departure_time stops  \
  2            2  AirAsia   I5-764       Delhi  Early_Morning  zero
  18          18  AirAsia   I5-747       Delhi        Evening   one
  19          19  AirAsia   I5-747       Delhi        Evening   one
  27          27  AirAsia   I5-744       Delhi        Morning   one
  48          48  AirAsia   I5-784       Delhi        Evening   one
  ...        ...      ...      ...         ...            ...   ...
  206538  206538  AirAsia  I5-1229     Chennai          Night   one
  206539  206539  AirAsia  I5-2462     Chennai          Night   one
  206591  206591  AirAsia   I5-517     Chennai        Morning  zero
  206616  206616  AirAsia  I5-1229     Chennai          Night   one
  206617  206617  AirAsia  I5-2462     Chennai          Night   one

           arrival_time destination_city    class  duration  days_left  price
  2       Early_Morning           Mumbai  Economy      2.17          1   5956
  18      Early_Morning           Mumbai  Economy     12.25          1   5949
  19            Morning           Mumbai  Economy     16.33          1   5949
  27          Afternoon           Mumbai  Economy      5.83          1   8869
  48      Early_Morning           Mumbai  Economy     15.17          1  12539
  ...               ...              ...      ...       ...        ...    ...
  206538        Morning        Hyderabad  Economy      9.25         48   1550
  206539        Morning        Hyderabad  Economy     10.17         48   1550
  206591        Morning        Hyderabad  Economy      1.17         49   1105
  206616        Morning        Hyderabad  Economy      9.25         49   1550
  206617        Morning        Hyderabad  Economy     10.17         49   1550

  [16098 rows x 12 columns]),
 ('Air_India',
           index    airline  flight source_city departure_time stops  \
  16          16  Air_India  AI-887       Delhi  Early_Morning  zero
  17          17  Air_India  AI-665       Delhi  Early_Morning  zero
  23          23  Air_India  AI-441       Delhi        Evening   one
  37          37  Air_India  AI-453       Delhi  Early_Morning   one
  40          40  Air_India  AI-504       Delhi          Night   one
  ...        ...        ...     ...         ...            ...   ...
  300143  300143  Air_India  AI-440     Chennai  Early_Morning   one
  300144  300144  Air_India  AI-539     Chennai        Evening   one
  300145  300145  Air_India  AI-430     Chennai        Morning   one
  300146  300146  Air_India  AI-440     Chennai  Early_Morning   one
  300147  300147  Air_India  AI-569     Chennai  Early_Morning   one

         arrival_time destination_city     class  duration  days_left  price
  16          Morning           Mumbai   Economy      2.08          1   5955
  17          Morning           Mumbai   Economy      2.17          1   5955
  23            Night           Mumbai   Economy      3.75          1   5955
  37        Afternoon           Mumbai   Economy      8.83          1  11900
  40          Morning           Mumbai   Economy     11.00          1  12150
  ...             ...              ...       ...       ...        ...    ...
  300143        Night        Hyderabad  Business     17.42         49  51345
  300144      Morning        Hyderabad  Business     18.92         49  51345
  300145      Morning        Hyderabad  Business     23.08         49  51345
  300146      Morning        Hyderabad  Business     26.83         49  51345
  300147        Night        Hyderabad  Business     17.25         49  68739

  [80892 rows x 12 columns]),
 ('GO_FIRST',
           index   airline  flight source_city departure_time stops  \
  8            8  GO_FIRST  G8-334       Delhi  Early_Morning  zero
  9            9  GO_FIRST  G8-336       Delhi      Afternoon  zero
  10          10  GO_FIRST  G8-392       Delhi      Afternoon  zero
  11          11  GO_FIRST  G8-338       Delhi        Morning  zero
  20          20  GO_FIRST  G8-266       Delhi  Early_Morning   one
  ...        ...       ...     ...         ...            ...   ...
  206320  206320  GO_FIRST  G8-911     Chennai      Afternoon   one
  206352  206352  GO_FIRST  G8-504     Chennai      Afternoon  zero
  206432  206432  GO_FIRST  G8-504     Chennai      Afternoon  zero
  206509  206509  GO_FIRST  G8-504     Chennai      Afternoon  zero
  206589  206589  GO_FIRST  G8-504     Chennai      Afternoon  zero

         arrival_time destination_city    class  duration  days_left  price
  8           Morning           Mumbai  Economy      2.17          1   5954
  9           Evening           Mumbai  Economy      2.25          1   5954
  10          Evening           Mumbai  Economy      2.25          1   5954
  11        Afternoon           Mumbai  Economy      2.33          1   5954
  20          Evening           Mumbai  Economy     11.75          1   5954
  ...             ...              ...      ...       ...        ...    ...
  206320        Night        Hyderabad  Economy      7.58         45   4933
  206352    Afternoon        Hyderabad  Economy      1.00         46   1105
  206432    Afternoon        Hyderabad  Economy      1.00         47   1105
  206509    Afternoon        Hyderabad  Economy      1.00         48   1105
  206589    Afternoon        Hyderabad  Economy      1.00         49   1105

  [23173 rows x 12 columns]),
 ('Indigo',
           index airline     flight source_city departure_time stops  \
  12          12  Indigo    6E-5001       Delhi  Early_Morning  zero
  13          13  Indigo    6E-6202       Delhi        Morning  zero
  14          14  Indigo     6E-549       Delhi      Afternoon  zero
  15          15  Indigo    6E-6278       Delhi        Morning  zero
  24          24  Indigo    6E-5328       Delhi        Morning  zero
  ...        ...     ...        ...         ...            ...   ...
  206612  206612  Indigo  6.00E-156     Chennai          Night  zero
  206613  206613  Indigo     6E-562     Chennai        Evening  zero
  206614  206614  Indigo    6E-6215     Chennai        Evening  zero
  206615  206615  Indigo  6.00E-193     Chennai        Evening  zero
  206650  206650  Indigo    6E-7193     Chennai  Early_Morning   one

         arrival_time destination_city    class  duration  days_left  price
  12          Morning           Mumbai  Economy      2.17          1   5955
  13        Afternoon           Mumbai  Economy      2.17          1   5955
  14          Evening           Mumbai  Economy      2.25          1   5955
  15          Morning           Mumbai  Economy      2.33          1   5955
  24          Morning           Mumbai  Economy      2.50          1   6165
  ...             ...              ...      ...       ...        ...    ...
  206612        Night        Hyderabad  Economy      1.25         49   1551
  206613      Evening        Hyderabad  Economy      1.33         49   1551
  206614      Evening        Hyderabad  Economy      1.33         49   1551
  206615        Night        Hyderabad  Economy      1.33         49   1551
  206650    Afternoon        Hyderabad  Economy      6.67         49   5410

  [43120 rows x 12 columns]),
 ('SpiceJet',
           index   airline   flight source_city departure_time stops  \
  0            0  SpiceJet  SG-8709       Delhi        Evening  zero
  1            1  SpiceJet  SG-8157       Delhi  Early_Morning  zero
  28          28  SpiceJet  SG-8169       Delhi        Evening  zero
  38          38  SpiceJet  SG-2976       Delhi        Evening   one
  39          39  SpiceJet  SG-2976       Delhi        Evening   one
  ...        ...       ...      ...         ...            ...   ...
  205560  205560  SpiceJet   SG-731     Chennai  Early_Morning  zero
  205644  205644  SpiceJet   SG-731     Chennai  Early_Morning  zero
  205822  205822  SpiceJet   SG-731     Chennai  Early_Morning  zero
  206005  206005  SpiceJet   SG-731     Chennai  Early_Morning  zero
  206184  206184  SpiceJet   SG-731     Chennai  Early_Morning  zero

           arrival_time destination_city    class  duration  days_left  price
  0               Night           Mumbai  Economy      2.17          1   5953
  1             Morning           Mumbai  Economy      2.33          1   5953
  28              Night           Mumbai  Economy      2.33          1  10260
  38              Night           Mumbai  Economy      4.50          1  12123
  39            Morning           Mumbai  Economy     15.25          1  12123
  ...               ...              ...      ...       ...        ...    ...
  205560  Early_Morning        Hyderabad  Economy      1.25         37   1551
  205644  Early_Morning        Hyderabad  Economy      1.25         38   1106
  205822  Early_Morning        Hyderabad  Economy      1.25         40   1106
  206005  Early_Morning        Hyderabad  Economy      1.25         42   1106
  206184  Early_Morning        Hyderabad  Economy      1.25         44   1106

  [9011 rows x 12 columns]),
 ('Vistara',
           index  airline  flight source_city departure_time stops arrival_time  \
  3            3  Vistara  UK-995       Delhi        Morning  zero    Afternoon
  4            4  Vistara  UK-963       Delhi        Morning  zero      Morning
  5            5  Vistara  UK-945       Delhi        Morning  zero    Afternoon
  6            6  Vistara  UK-927       Delhi        Morning  zero      Morning
  7            7  Vistara  UK-951       Delhi      Afternoon  zero      Evening
  ...        ...      ...     ...         ...            ...   ...          ...
  300148  300148  Vistara  UK-822     Chennai        Morning   one      Evening
  300149  300149  Vistara  UK-826     Chennai      Afternoon   one        Night
  300150  300150  Vistara  UK-832     Chennai  Early_Morning   one        Night
  300151  300151  Vistara  UK-828     Chennai  Early_Morning   one      Evening
  300152  300152  Vistara  UK-822     Chennai        Morning   one      Evening

         destination_city     class  duration  days_left  price
  3                Mumbai   Economy      2.25          1   5955
  4                Mumbai   Economy      2.33          1   5955
  5                Mumbai   Economy      2.33          1   5955
  6                Mumbai   Economy      2.08          1   6060
  7                Mumbai   Economy      2.17          1   6060
  ...                 ...       ...       ...        ...    ...
  300148        Hyderabad  Business     10.08         49  69265
  300149        Hyderabad  Business     10.42         49  77105
  300150        Hyderabad  Business     13.83         49  79099
  300151        Hyderabad  Business     10.00         49  81585
  300152        Hyderabad  Business     10.08         49  81585

  [127859 rows x 12 columns])]

to get airline with specific name

In [ ]:
group_result.get_group('Vistara')

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
5,5,Vistara,UK-945,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.33,1,5955
6,6,Vistara,UK-927,Delhi,Morning,zero,Morning,Mumbai,Economy,2.08,1,6060
7,7,Vistara,UK-951,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.17,1,6060
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

using forloop gruoping by airlines,flight,source city

In [ ]:
for flight,source_city in group_result:
  print(flight)
  print(source_city)

AirAsia
         index  airline   flight source_city departure_time stops  \
2            2  AirAsia   I5-764       Delhi  Early_Morning  zero
18          18  AirAsia   I5-747       Delhi        Evening   one
19          19  AirAsia   I5-747       Delhi        Evening   one
27          27  AirAsia   I5-744       Delhi        Morning   one
48          48  AirAsia   I5-784       Delhi        Evening   one
...        ...      ...      ...         ...            ...   ...
206538  206538  AirAsia  I5-1229     Chennai          Night   one
206539  206539  AirAsia  I5-2462     Chennai          Night   one
206591  206591  AirAsia   I5-517     Chennai        Morning  zero
206616  206616  AirAsia  I5-1229     Chennai          Night   one
206617  206617  AirAsia  I5-2462     Chennai          Night   one

         arrival_time destination_city    class  duration  days_left  price
2       Early_Morning           Mumbai  Economy      2.17          1   5956
18      Early_Morning           Mumbai  Economy     12.25          1   5949
19            Morning           Mumbai  Economy     16.33          1   5949
27          Afternoon           Mumbai  Economy      5.83          1   8869
48      Early_Morning           Mumbai  Economy     15.17          1  12539
...               ...              ...      ...       ...        ...    ...
206538        Morning        Hyderabad  Economy      9.25         48   1550
206539        Morning        Hyderabad  Economy     10.17         48   1550
206591        Morning        Hyderabad  Economy      1.17         49   1105
206616        Morning        Hyderabad  Economy      9.25         49   1550
206617        Morning        Hyderabad  Economy     10.17         49   1550

[16098 rows x 12 columns]
Air_India
         index    airline  flight source_city departure_time stops  \
16          16  Air_India  AI-887       Delhi  Early_Morning  zero
17          17  Air_India  AI-665       Delhi  Early_Morning  zero
23          23  Air_India  AI-441       Delhi        Evening   one
37          37  Air_India  AI-453       Delhi  Early_Morning   one
40          40  Air_India  AI-504       Delhi          Night   one
...        ...        ...     ...         ...            ...   ...
300143  300143  Air_India  AI-440     Chennai  Early_Morning   one
300144  300144  Air_India  AI-539     Chennai        Evening   one
300145  300145  Air_India  AI-430     Chennai        Morning   one
300146  300146  Air_India  AI-440     Chennai  Early_Morning   one
300147  300147  Air_India  AI-569     Chennai  Early_Morning   one

       arrival_time destination_city     class  duration  days_left  price
16          Morning           Mumbai   Economy      2.08          1   5955
17          Morning           Mumbai   Economy      2.17          1   5955
23            Night           Mumbai   Economy      3.75          1   5955
37        Afternoon           Mumbai   Economy      8.83          1  11900
40          Morning           Mumbai   Economy     11.00          1  12150
...             ...              ...       ...       ...        ...    ...
300143        Night        Hyderabad  Business     17.42         49  51345
300144      Morning        Hyderabad  Business     18.92         49  51345
300145      Morning        Hyderabad  Business     23.08         49  51345
300146      Morning        Hyderabad  Business     26.83         49  51345
300147        Night        Hyderabad  Business     17.25         49  68739

[80892 rows x 12 columns]
GO_FIRST
         index   airline  flight source_city departure_time stops  \
8            8  GO_FIRST  G8-334       Delhi  Early_Morning  zero
9            9  GO_FIRST  G8-336       Delhi      Afternoon  zero
10          10  GO_FIRST  G8-392       Delhi      Afternoon  zero
11          11  GO_FIRST  G8-338       Delhi        Morning  zero
20          20  GO_FIRST  G8-266       Delhi  Early_Morning   one
...        ...       ...     ...         ...            ...   ...
206320  206320  GO_FIRST  G8-911     Chennai      Afternoon   one
206352  206352  GO_FIRST  G8-504     Chennai      Afternoon  zero
206432  206432  GO_FIRST  G8-504     Chennai      Afternoon  zero
206509  206509  GO_FIRST  G8-504     Chennai      Afternoon  zero
206589  206589  GO_FIRST  G8-504     Chennai      Afternoon  zero

       arrival_time destination_city    class  duration  days_left  price
8           Morning           Mumbai  Economy      2.17          1   5954
9           Evening           Mumbai  Economy      2.25          1   5954
10          Evening           Mumbai  Economy      2.25          1   5954
11        Afternoon           Mumbai  Economy      2.33          1   5954
20          Evening           Mumbai  Economy     11.75          1   5954
...             ...              ...      ...       ...        ...    ...
206320        Night        Hyderabad  Economy      7.58         45   4933
206352    Afternoon        Hyderabad  Economy      1.00         46   1105
206432    Afternoon        Hyderabad  Economy      1.00         47   1105
206509    Afternoon        Hyderabad  Economy      1.00         48   1105
206589    Afternoon        Hyderabad  Economy      1.00         49   1105

[23173 rows x 12 columns]
Indigo
         index airline     flight source_city departure_time stops  \
12          12  Indigo    6E-5001       Delhi  Early_Morning  zero
13          13  Indigo    6E-6202       Delhi        Morning  zero
14          14  Indigo     6E-549       Delhi      Afternoon  zero
15          15  Indigo    6E-6278       Delhi        Morning  zero
24          24  Indigo    6E-5328       Delhi        Morning  zero
...        ...     ...        ...         ...            ...   ...
206612  206612  Indigo  6.00E-156     Chennai          Night  zero
206613  206613  Indigo     6E-562     Chennai        Evening  zero
206614  206614  Indigo    6E-6215     Chennai        Evening  zero
206615  206615  Indigo  6.00E-193     Chennai        Evening  zero
206650  206650  Indigo    6E-7193     Chennai  Early_Morning   one

       arrival_time destination_city    class  duration  days_left  price
12          Morning           Mumbai  Economy      2.17          1   5955
13        Afternoon           Mumbai  Economy      2.17          1   5955
14          Evening           Mumbai  Economy      2.25          1   5955
15          Morning           Mumbai  Economy      2.33          1   5955
24          Morning           Mumbai  Economy      2.50          1   6165
...             ...              ...      ...       ...        ...    ...
206612        Night        Hyderabad  Economy      1.25         49   1551
206613      Evening        Hyderabad  Economy      1.33         49   1551
206614      Evening        Hyderabad  Economy      1.33         49   1551
206615        Night        Hyderabad  Economy      1.33         49   1551
206650    Afternoon        Hyderabad  Economy      6.67         49   5410

[43120 rows x 12 columns]
SpiceJet
         index   airline   flight source_city departure_time stops  \
0            0  SpiceJet  SG-8709       Delhi        Evening  zero
1            1  SpiceJet  SG-8157       Delhi  Early_Morning  zero
28          28  SpiceJet  SG-8169       Delhi        Evening  zero
38          38  SpiceJet  SG-2976       Delhi        Evening   one
39          39  SpiceJet  SG-2976       Delhi        Evening   one
...        ...       ...      ...         ...            ...   ...
205560  205560  SpiceJet   SG-731     Chennai  Early_Morning  zero
205644  205644  SpiceJet   SG-731     Chennai  Early_Morning  zero
205822  205822  SpiceJet   SG-731     Chennai  Early_Morning  zero
206005  206005  SpiceJet   SG-731     Chennai  Early_Morning  zero
206184  206184  SpiceJet   SG-731     Chennai  Early_Morning  zero

         arrival_time destination_city    class  duration  days_left  price
0               Night           Mumbai  Economy      2.17          1   5953
1             Morning           Mumbai  Economy      2.33          1   5953
28              Night           Mumbai  Economy      2.33          1  10260
38              Night           Mumbai  Economy      4.50          1  12123
39            Morning           Mumbai  Economy     15.25          1  12123
...               ...              ...      ...       ...        ...    ...
205560  Early_Morning        Hyderabad  Economy      1.25         37   1551
205644  Early_Morning        Hyderabad  Economy      1.25         38   1106
205822  Early_Morning        Hyderabad  Economy      1.25         40   1106
206005  Early_Morning        Hyderabad  Economy      1.25         42   1106
206184  Early_Morning        Hyderabad  Economy      1.25         44   1106

[9011 rows x 12 columns]
Vistara
         index  airline  flight source_city departure_time stops arrival_time  \
3            3  Vistara  UK-995       Delhi        Morning  zero    Afternoon
4            4  Vistara  UK-963       Delhi        Morning  zero      Morning
5            5  Vistara  UK-945       Delhi        Morning  zero    Afternoon
6            6  Vistara  UK-927       Delhi        Morning  zero      Morning
7            7  Vistara  UK-951       Delhi      Afternoon  zero      Evening
...        ...      ...     ...         ...            ...   ...          ...
300148  300148  Vistara  UK-822     Chennai        Morning   one      Evening
300149  300149  Vistara  UK-826     Chennai      Afternoon   one        Night
300150  300150  Vistara  UK-832     Chennai  Early_Morning   one        Night
300151  300151  Vistara  UK-828     Chennai  Early_Morning   one      Evening
300152  300152  Vistara  UK-822     Chennai        Morning   one      Evening

       destination_city     class  duration  days_left  price
3                Mumbai   Economy      2.25          1   5955
4                Mumbai   Economy      2.33          1   5955
5                Mumbai   Economy      2.33          1   5955
6                Mumbai   Economy      2.08          1   6060
7                Mumbai   Economy      2.17          1   6060
...                 ...       ...       ...        ...    ...
300148        Hyderabad  Business     10.08         49  69265
300149        Hyderabad  Business     10.42         49  77105
300150        Hyderabad  Business     13.83         49  79099
300151        Hyderabad  Business     10.00         49  81585
300152        Hyderabad  Business     10.08         49  81585

[127859 rows x 12 columns]

###Group operations

to get maximum values of airlines respepectively

In [ ]:
group_result.max()

,index,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
airline,,,,,,,,,,,
AirAsia,206617,I5-996,Mumbai,Night,zero,Night,Mumbai,Economy,19.58,49,31917
Air_India,300147,AI-9991,Mumbai,Night,zero,Night,Mumbai,Economy,49.83,49,90970
GO_FIRST,206589,G8-962,Mumbai,Night,zero,Night,Mumbai,Economy,22.50,49,32803
Indigo,206650,6E-998,Mumbai,Night,zero,Night,Mumbai,Economy,15.42,49,31952
SpiceJet,206184,SG-9974,Mumbai,Night,zero,Night,Mumbai,Economy,27.92,49,34158
Vistara,300152,UK-996,Mumbai,Night,zero,Night,Mumbai,Economy,47.08,49,123071

separatively:-

In [ ]:
group_result.get_group('Vistara').max()

index                300152
airline             Vistara
flight               UK-996
source_city          Mumbai
departure_time        Night
stops                  zero
arrival_time          Night
destination_city     Mumbai
class               Economy
duration              47.08
days_left                49
price                123071
dtype: object

###Group by multiple columns

group by source_city,destination_city

In [ ]:
grp=df.groupby(['flight','source_city'])
list(grp)

[(('0.00E+00', 'Bangalore'),
           index airline    flight source_city departure_time stops  \
  97026    97026  Indigo  0.00E+00   Bangalore        Evening   one
  97174    97174  Indigo  0.00E+00   Bangalore        Evening   one
  97222    97222  Indigo  0.00E+00   Bangalore        Evening   one
  97247    97247  Indigo  0.00E+00   Bangalore        Evening   one
  97410    97410  Indigo  0.00E+00   Bangalore        Evening   one
  97470    97470  Indigo  0.00E+00   Bangalore        Evening   one
  97603    97603  Indigo  0.00E+00   Bangalore        Evening   one
  97604    97604  Indigo  0.00E+00   Bangalore        Evening   one
  97793    97793  Indigo  0.00E+00   Bangalore        Evening   one
  97798    97798  Indigo  0.00E+00   Bangalore        Evening   one
  97979    97979  Indigo  0.00E+00   Bangalore        Evening   one
  98095    98095  Indigo  0.00E+00   Bangalore        Evening   one
  98174    98174  Indigo  0.00E+00   Bangalore        Evening   one
  98232    98232  Indigo  0.00E+00   Bangalore        Evening   one
  98363    98363  Indigo  0.00E+00   Bangalore        Evening   one
  98364    98364  Indigo  0.00E+00   Bangalore        Evening   one
  98558    98558  Indigo  0.00E+00   Bangalore        Evening   one
  98608    98608  Indigo  0.00E+00   Bangalore        Evening   one
  98742    98742  Indigo  0.00E+00   Bangalore        Evening   one
  98743    98743  Indigo  0.00E+00   Bangalore        Evening   one
  98936    98936  Indigo  0.00E+00   Bangalore        Evening   one
  98939    98939  Indigo  0.00E+00   Bangalore        Evening   one
  99124    99124  Indigo  0.00E+00   Bangalore        Evening   one
  99125    99125  Indigo  0.00E+00   Bangalore        Evening   one
  99327    99327  Indigo  0.00E+00   Bangalore        Evening   one
  99362    99362  Indigo  0.00E+00   Bangalore        Evening   one
  99485    99485  Indigo  0.00E+00   Bangalore        Evening   one
  99530    99530  Indigo  0.00E+00   Bangalore        Evening   one
  99664    99664  Indigo  0.00E+00   Bangalore        Evening   one
  99704    99704  Indigo  0.00E+00   Bangalore        Evening   one
  99869    99869  Indigo  0.00E+00   Bangalore        Evening   one
  99903    99903  Indigo  0.00E+00   Bangalore        Evening   one
  100054  100054  Indigo  0.00E+00   Bangalore        Evening   one
  100055  100055  Indigo  0.00E+00   Bangalore        Evening   one
  100234  100234  Indigo  0.00E+00   Bangalore        Evening   one
  100235  100235  Indigo  0.00E+00   Bangalore        Evening   one
  100428  100428  Indigo  0.00E+00   Bangalore        Evening   one
  100466  100466  Indigo  0.00E+00   Bangalore        Evening   one
  100643  100643  Indigo  0.00E+00   Bangalore        Evening   one
  100735  100735  Indigo  0.00E+00   Bangalore        Evening   one
  100819  100819  Indigo  0.00E+00   Bangalore        Evening   one
  100838  100838  Indigo  0.00E+00   Bangalore        Evening   one
  100987  100987  Indigo  0.00E+00   Bangalore        Evening   one
  101004  101004  Indigo  0.00E+00   Bangalore        Evening   one
  101145  101145  Indigo  0.00E+00   Bangalore        Evening   one
  101186  101186  Indigo  0.00E+00   Bangalore        Evening   one
  101329  101329  Indigo  0.00E+00   Bangalore        Evening   one
  101371  101371  Indigo  0.00E+00   Bangalore        Evening   one
  101548  101548  Indigo  0.00E+00   Bangalore        Evening   one
  101560  101560  Indigo  0.00E+00   Bangalore        Evening   one
  101700  101700  Indigo  0.00E+00   Bangalore        Evening   one

         arrival_time destination_city    class  duration  days_left  price
  97026    Late_Night           Mumbai  Economy      7.08         19   3957
  97174    Late_Night           Mumbai  Economy      4.83         19   8832
  97222    Late_Night           Mumbai  Economy      7.08         20   3957
  97247    Late_Night           Mumbai  Economy      4.83         20   4557
  97410    Late_Night           Mumbai  Economy      7.08         21   3957
  97470    Late_Night           Mumbai  Economy      4.83         21   6092
  97603    Late_Night           Mumbai  Economy      4.83         22   3957
  97604    Late_Night           Mumbai  Economy      7.08         22   3957
  97793    Late_Night           Mumbai  Economy      7.08         23   3957
  97798    Late_Night           Mumbai  Economy      4.83         23   4171
  97979    Late_Night           Mumbai  Economy      7.08         24   3957
  98095    Late_Night           Mumbai  Economy      4.83         24   6748
  98174    Late_Night           Mumbai  Economy      7.08         25   3957
  98232    Late_Night           Mumbai  Economy      4.83         25   5178
  98363    Late_Night           Mumbai  Economy      4.83         26   3957
  98364    Late_Night           Mumbai  Economy      7.08         26   3957
  98558    Late_Night           Mumbai  Economy      7.08         27   3957
  98608    Late_Night           Mumbai  Economy      4.83         27   5178
  98742    Late_Night           Mumbai  Economy      4.83         28   3957
  98743    Late_Night           Mumbai  Economy      7.08         28   3957
  98936    Late_Night           Mumbai  Economy      4.83         29   3957
  98939    Late_Night           Mumbai  Economy      7.08         29   3957
  99124    Late_Night           Mumbai  Economy      4.83         30   3957
  99125    Late_Night           Mumbai  Economy      7.08         30   3957
  99327    Late_Night           Mumbai  Economy      7.08         31   3957
  99362    Late_Night           Mumbai  Economy      4.83         31   5853
  99485    Late_Night           Mumbai  Economy      4.83         32   2201
  99530    Late_Night           Mumbai  Economy      7.08         32   3957
  99664    Late_Night           Mumbai  Economy      4.83         33   2201
  99704    Late_Night           Mumbai  Economy      7.08         33   3957
  99869    Late_Night           Mumbai  Economy      4.83         34   3153
  99903    Late_Night           Mumbai  Economy      7.08         34   4750
  100054   Late_Night           Mumbai  Economy      4.83         35   4156
  100055   Late_Night           Mumbai  Economy      7.08         35   4156
  100234   Late_Night           Mumbai  Economy      4.83         36   3957
  100235   Late_Night           Mumbai  Economy      7.08         36   3957
  100428   Late_Night           Mumbai  Economy      4.83         37   3957
  100466   Late_Night           Mumbai  Economy      7.08         37   5012
  100643   Late_Night           Mumbai  Economy      7.08         38   5853
  100735   Late_Night           Mumbai  Economy      4.83         38   7220
  100819   Late_Night           Mumbai  Economy      7.08         39   3957
  100838   Late_Night           Mumbai  Economy      4.83         39   5012
  100987   Late_Night           Mumbai  Economy      4.83         40   3153
  101004   Late_Night           Mumbai  Economy      7.08         40   3957
  101145   Late_Night           Mumbai  Economy      4.83         41   2201
  101186   Late_Night           Mumbai  Economy      7.08         41   3957
  101329   Late_Night           Mumbai  Economy      4.83         42   2201
  101371   Late_Night           Mumbai  Economy      7.08         42   3957
  101548   Late_Night           Mumbai  Economy      7.08         43   3153
  101560   Late_Night           Mumbai  Economy      4.83         43   3957
  101700   Late_Night           Mumbai  Economy      4.83         44   2201  ),
 (('6.00E-102', 'Hyderabad'),
           index airline     flight source_city departure_time stops  \
  167218  167218  Indigo  6.00E-102   Hyderabad        Evening   one
  167444  167444  Indigo  6.00E-102   Hyderabad        Evening   one
  167667  167667  Indigo  6.00E-102   Hyderabad        Evening   one
  168011  168011  Indigo  6.00E-102   Hyderabad        Evening   one
  168236  168236  Indigo  6.00E-102   Hyderabad        Evening   one
  168460  168460  Indigo  6.00E-102   Hyderabad        Evening   one
  168775  168775  Indigo  6.00E-102   Hyderabad        Evening   one
  169021  169021  Indigo  6.00E-102   Hyderabad        Evening   one
  169243  169243  Indigo  6.00E-102   Hyderabad        Evening   one
  169558  169558  Indigo  6.00E-102   Hyderabad        Evening   one
  169780  169780  Indigo  6.00E-102   Hyderabad        Evening   one
  170001  170001  Indigo  6.00E-102   Hyderabad        Evening   one
  170116  170116  Indigo  6.00E-102   Hyderabad        Evening   one
  170248  170248  Indigo  6.00E-102   Hyderabad        Evening   one
  170372  170372  Indigo  6.00E-102   Hyderabad        Evening   one
  170495  170495  Indigo  6.00E-102   Hyderabad        Evening   one
  170615  170615  Indigo  6.00E-102   Hyderabad        Evening   one
  175758  175758  Indigo  6.00E-102   Hyderabad        Evening   one
  175882  175882  Indigo  6.00E-102   Hyderabad        Evening   one
  176001  176001  Indigo  6.00E-102   Hyderabad        Evening   one
  176117  176117  Indigo  6.00E-102   Hyderabad        Evening   one
  176234  176234  Indigo  6.00E-102   Hyderabad        Evening   one
  177675  177675  Indigo  6.00E-102   Hyderabad        Evening  zero
  177865  177865  Indigo  6.00E-102   Hyderabad        Evening  zero
  178043  178043  Indigo  6.00E-102   Hyderabad        Evening  zero
  178331  178331  Indigo  6.00E-102   Hyderabad        Evening  zero
  178516  178516  Indigo  6.00E-102   Hyderabad        Evening  zero
  178705  178705  Indigo  6.00E-102   Hyderabad        Evening  zero
  178997  178997  Indigo  6.00E-102   Hyderabad        Evening  zero
  179168  179168  Indigo  6.00E-102   Hyderabad        Evening  zero
  179354  179354  Indigo  6.00E-102   Hyderabad        Evening  zero
  179654  179654  Indigo  6.00E-102   Hyderabad        Evening  zero
  179838  179838  Indigo  6.00E-102   Hyderabad        Evening  zero
  180023  180023  Indigo  6.00E-102   Hyderabad        Evening  zero
  180113  180113  Indigo  6.00E-102   Hyderabad        Evening  zero
  180198  180198  Indigo  6.00E-102   Hyderabad        Evening  zero
  180282  180282  Indigo  6.00E-102   Hyderabad        Evening  zero
  180362  180362  Indigo  6.00E-102   Hyderabad        Evening  zero
  180442  180442  Indigo  6.00E-102   Hyderabad        Evening  zero

         arrival_time destination_city    class  duration  days_left  price
  167218        Night        Bangalore  Economy      4.42         19   3072
  167444        Night        Bangalore  Economy      4.42         21   3072
  167667        Night        Bangalore  Economy      4.42         23   3072
  168011        Night        Bangalore  Economy      4.42         26   3072
  168236        Night        Bangalore  Economy      4.42         28   3072
  168460        Night        Bangalore  Economy      4.42         30   3072
  168775        Night        Bangalore  Economy      4.42         33   1755
  169021        Night        Bangalore  Economy      4.42         35   2861
  169243        Night        Bangalore  Economy      4.42         37   2861
  169558        Night        Bangalore  Economy      4.42         40   1755
  169780        Night        Bangalore  Economy      4.42         42   1755
  170001        Night        Bangalore  Economy      4.42         44   1755
  170116        Night        Bangalore  Economy      4.42         45   1755
  170248        Night        Bangalore  Economy      4.42         46   1755
  170372        Night        Bangalore  Economy      4.42         47   1755
  170495        Night        Bangalore  Economy      4.42         48   1755
  170615        Night        Bangalore  Economy      4.42         49   1755
  175758        Night          Kolkata  Economy      5.67         45   2057
  175882        Night          Kolkata  Economy      5.67         46   2057
  176001        Night          Kolkata  Economy      5.67         47   2057
  176117        Night          Kolkata  Economy      5.67         48   2057
  176234        Night          Kolkata  Economy      5.67         49   2057
  177675      Evening          Chennai  Economy      1.25         19   1788
  177865      Evening          Chennai  Economy      1.25         21   1788
  178043      Evening          Chennai  Economy      1.25         23   1788
  178331      Evening          Chennai  Economy      1.25         26   1788
  178516      Evening          Chennai  Economy      1.25         28   1788
  178705      Evening          Chennai  Economy      1.25         30   1788
  178997      Evening          Chennai  Economy      1.25         33   1788
  179168      Evening          Chennai  Economy      1.25         35   1788
  179354      Evening          Chennai  Economy      1.25         37   1788
  179654      Evening          Chennai  Economy      1.25         40   1788
  179838      Evening          Chennai  Economy      1.25         42   1788
  180023      Evening          Chennai  Economy      1.25         44   1788
  180113      Evening          Chennai  Economy      1.33         45   1788
  180198      Evening          Chennai  Economy      1.33         46   1788
  180282      Evening          Chennai  Economy      1.33         47   1788
  180362      Evening          Chennai  Economy      1.33         48   1788
  180442      Evening          Chennai  Economy      1.33         49   1788  ),
 (('6.00E-105', 'Chennai'),
           index airline     flight source_city departure_time stops  \
  202187  202187  Indigo  6.00E-105     Chennai      Afternoon   one
  202297  202297  Indigo  6.00E-105     Chennai      Afternoon   one
  202397  202397  Indigo  6.00E-105     Chennai      Afternoon   one
  202492  202492  Indigo  6.00E-105     Chennai      Afternoon   one
  202590  202590  Indigo  6.00E-105     Chennai      Afternoon   one

         arrival_time destination_city    class  duration  days_left  price
  202187        Night          Kolkata  Economy       7.5         45   4079
  202297        Night          Kolkata  Economy       7.5         46   4079
  202397        Night          Kolkata  Economy       7.5         47   4079
  202492        Night          Kolkata  Economy       7.5         48   4079
  202590        Night          Kolkata  Economy       7.5         49   4079  ),
 (('6.00E-113', 'Bangalore'),
           index airline     flight source_city departure_time stops  \
  94028    94028  Indigo  6.00E-113   Bangalore        Morning   one
  94158    94158  Indigo  6.00E-113   Bangalore        Morning   one
  94272    94272  Indigo  6.00E-113   Bangalore        Morning   one
  94407    94407  Indigo  6.00E-113   Bangalore        Morning   one
  94551    94551  Indigo  6.00E-113   Bangalore        Morning   one
  94698    94698  Indigo  6.00E-113   Bangalore        Morning   one
  94867    94867  Indigo  6.00E-113   Bangalore        Morning   one
  95031    95031  Indigo  6.00E-113   Bangalore        Morning   one
  95180    95180  Indigo  6.00E-113   Bangalore        Morning   one
  95380    95380  Indigo  6.00E-113   Bangalore        Morning   one
  95649    95649  Indigo  6.00E-113   Bangalore        Morning   one
  95712    95712  Indigo  6.00E-113   Bangalore        Morning   one
  95727    95727  Indigo  6.00E-113   Bangalore        Morning   one
  95920    95920  Indigo  6.00E-113   Bangalore        Morning   one
  96112    96112  Indigo  6.00E-113   Bangalore        Morning   one
  96277    96277  Indigo  6.00E-113   Bangalore        Morning   one
  96588    96588  Indigo  6.00E-113   Bangalore        Morning   one
  96683    96683  Indigo  6.00E-113   Bangalore        Morning   one
  96900    96900  Indigo  6.00E-113   Bangalore        Morning   one
  97039    97039  Indigo  6.00E-113   Bangalore        Morning   one
  97082    97082  Indigo  6.00E-113   Bangalore        Morning   one
  97251    97251  Indigo  6.00E-113   Bangalore        Morning   one
  97431    97431  Indigo  6.00E-113   Bangalore        Morning   one
  97615    97615  Indigo  6.00E-113   Bangalore        Morning   one
  97849    97849  Indigo  6.00E-113   Bangalore        Morning   one
  98029    98029  Indigo  6.00E-113   Bangalore        Morning   one
  98201    98201  Indigo  6.00E-113   Bangalore        Morning   one
  98378    98378  Indigo  6.00E-113   Bangalore        Morning   one
  98379    98379  Indigo  6.00E-113   Bangalore        Morning   one
  98582    98582  Indigo  6.00E-113   Bangalore        Morning   one
  98767    98767  Indigo  6.00E-113   Bangalore        Morning   one
  98952    98952  Indigo  6.00E-113   Bangalore        Morning   one
  99149    99149  Indigo  6.00E-113   Bangalore        Morning   one
  99352    99352  Indigo  6.00E-113   Bangalore        Morning   one
  99486    99486  Indigo  6.00E-113   Bangalore        Morning   one
  99663    99663  Indigo  6.00E-113   Bangalore        Morning   one
  99665    99665  Indigo  6.00E-113   Bangalore        Morning   one
  99845    99845  Indigo  6.00E-113   Bangalore        Morning   one
  100049  100049  Indigo  6.00E-113   Bangalore        Morning   one
  100241  100241  Indigo  6.00E-113   Bangalore        Morning   one
  100451  100451  Indigo  6.00E-113   Bangalore        Morning   one
  100631  100631  Indigo  6.00E-113   Bangalore        Morning   one
  100778  100778  Indigo  6.00E-113   Bangalore        Morning   one
  100963  100963  Indigo  6.00E-113   Bangalore        Morning   one
  100964  100964  Indigo  6.00E-113   Bangalore        Morning   one
  101146  101146  Indigo  6.00E-113   Bangalore        Morning   one
  101330  101330  Indigo  6.00E-113   Bangalore        Morning   one
  101516  101516  Indigo  6.00E-113   Bangalore        Morning   one
  101734  101734  Indigo  6.00E-113   Bangalore        Morning   one

         arrival_time destination_city    class  duration  days_left  price
  94028     Afternoon           Mumbai  Economy      5.83          1   7462
  94158     Afternoon           Mumbai  Economy      5.83          2   8832
  94272     Afternoon           Mumbai  Economy      5.83          3   7005
  94407     Afternoon           Mumbai  Economy      5.83          4   5178
  94551     Afternoon           Mumbai  Economy      5.83          5   5178
  94698     Afternoon           Mumbai  Economy      5.83          6   5178
  94867     Afternoon           Mumbai  Economy      5.83          7   6548
  95031     Afternoon           Mumbai  Economy      5.83          8   6548
  95180     Afternoon           Mumbai  Economy      5.83          9   6092
  95380     Afternoon           Mumbai  Economy      5.83         10   9289
  95649     Afternoon           Mumbai  Economy      5.83         11  18723
  95712     Afternoon           Mumbai  Economy      4.17         12   5178
  95727     Afternoon           Mumbai  Economy      5.83         12   6092
  95920     Afternoon           Mumbai  Economy      5.83         13   6092
  96112     Afternoon           Mumbai  Economy      5.83         14   7462
  96277     Afternoon           Mumbai  Economy      5.83         15   5178
  96588     Afternoon           Mumbai  Economy      5.83         16   7462
  96683     Afternoon           Mumbai  Economy      5.83         17   5635
  96900     Afternoon           Mumbai  Economy      5.83         18   5635
  97039     Afternoon           Mumbai  Economy      4.17         19   4349
  97082     Afternoon           Mumbai  Economy      5.83         19   5178
  97251     Afternoon           Mumbai  Economy      5.83         20   4970
  97431     Afternoon           Mumbai  Economy      5.83         21   4550
  97615     Afternoon           Mumbai  Economy      5.83         22   4349
  97849     Afternoon           Mumbai  Economy      5.83         23   5178
  98029     Afternoon           Mumbai  Economy      5.83         24   5178
  98201     Afternoon           Mumbai  Economy      5.83         25   4550
  98378     Afternoon           Mumbai  Economy      4.17         26   4349

##Concat
It is used to concat two or more dataframes

In [ ]:
import pandas as pd
tcs={'id':[101,102,103,104],'name':['mithun','dipin','jose','rahul'],
     'age':[25,26,27,29]}

wipro={'id':[101,102,103,104],
       'name':['dev','sreenath','sreerag','shafeel'],
       'age':[24,24,27,26]}

tcs_emp=pd.DataFrame(tcs)
wipro_emp=pd.DataFrame(wipro)
tcs_emp

    id    name  age
0  101  mithun   25
1  102   dipin   26
2  103    jose   27
3  104   rahul   29

In [ ]:
wipro_emp

    id      name  age
0  101       dev   24
1  102  sreenath   24
2  103   sreerag   27
3  104   shafeel   26

In [ ]:
pd.concat([tcs_emp,wipro_emp])

    id      name  age
0  101    mithun   25
1  102     dipin   26
2  103      jose   27
3  104     rahul   29
0  101       dev   24
1  102  sreenath   24
2  103   sreerag   27
3  104   shafeel   26

ignore index-To get common index after concatenation

In [ ]:
pd.concat([tcs_emp,wipro_emp],ignore_index=True)

    id      name  age
0  101    mithun   25
1  102     dipin   26
2  103      jose   27
3  104     rahul   29
4  101       dev   24
5  102  sreenath   24
6  103   sreerag   27
7  104   shafeel   26

keys-To provide seperate keys for each concatenate data frames

In [ ]:
data=pd.concat([tcs_emp,wipro_emp],keys=['tcs','wipro'])
data

          id      name  age
tcs   0  101    mithun   25
      1  102     dipin   26
      2  103      jose   27
      3  104     rahul   29
wipro 0  101       dev   24
      1  102  sreenath   24
      2  103   sreerag   27
      3  104   shafeel   26

concatenating vertically

In [ ]:
data=pd.concat([tcs_emp,wipro_emp],axis=1)
data

    id    name  age   id      name  age
0  101  mithun   25  101       dev   24
1  102   dipin   26  102  sreenath   24
2  103    jose   27  103   sreerag   27
3  104   rahul   29  104   shafeel   26

concatinating a dataframe with a series

In [ ]:
salary=pd.Series([65000,75000,15000,25000],name='salary')
pd.concat([tcs_emp,salary],axis=1)

    id    name  age  salary
0  101  mithun   25   65000
1  102   dipin   26   75000
2  103    jose   27   15000
3  104   rahul   29   25000

##Merge
Merge is a process to merge two tables horizontally

In [ ]:
import pandas as pd
tcs={'id':[101,102,103,106],'name':['mithun','dipin','joe','rahul'],
     'age':[25,26,27,29]}

wipro={'id':[101,102,103,105],
       'name':['dev','sreenath','sreerag','shafeel'],
       'age':[24,24,27,26]}

tcs_emp=pd.DataFrame(tcs)
wipro_emp=pd.DataFrame(wipro)

tcs_emp=pd.DataFrame(tcs)
tcs_emp

    id    name  age
0  101  mithun   25
1  102   dipin   26
2  103     joe   27
3  106   rahul   29

In [ ]:
wipro_emp=pd.DataFrame(wipro)
wipro_emp

    id      name  age
0  101       dev   24
1  102  sreenath   24
2  103   sreerag   27
3  105   shafeel   26

In [ ]:
pd.merge(tcs_emp,wipro_emp,on='id')

    id  name_x  age_x    name_y  age_y
0  101  mithun     25       dev     24
1  102   dipin     26  sreenath     24
2  103     joe     27   sreerag     27

only  respective number will appear if on='id' given

suffixes

In [ ]:
pd.merge(tcs_emp,wipro_emp,on='id', suffixes=['left','right'])

    id nameleft  ageleft nameright  ageright
0  101   mithun       25       dev        24
1  102    dipin       26  sreenath        24
2  103      joe       27   sreerag        27

outer join

In [ ]:
pd.merge(tcs_emp,wipro_emp,on='id',how='outer')

    id  name_x  age_x    name_y  age_y
0  101  mithun   25.0       dev   24.0
1  102   dipin   26.0  sreenath   24.0
2  103     joe   27.0   sreerag   27.0
3  105     NaN    NaN   shafeel   26.0
4  106   rahul   29.0       NaN    NaN

In [ ]:
pd.merge(tcs_emp,wipro_emp,on='id',how='outer',indicator=True)

    id  name_x  age_x    name_y  age_y      _merge
0  101  mithun   25.0       dev   24.0        both
1  102   dipin   26.0  sreenath   24.0        both
2  103     joe   27.0   sreerag   27.0        both
3  105     NaN    NaN   shafeel   26.0  right_only
4  106   rahul   29.0       NaN    NaN   left_only

left join

In [ ]:
pd.merge(tcs_emp,wipro_emp,on='id',how='left')

    id  name_x  age_x    name_y  age_y
0  101  mithun     25       dev   24.0
1  102   dipin     26  sreenath   24.0
2  103     joe     27   sreerag   27.0
3  106   rahul     29       NaN    NaN

right join

In [ ]:
pd.merge(tcs_emp,wipro_emp,on='id',how='right')

    id  name_x  age_x    name_y  age_y
0  101  mithun   25.0       dev     24
1  102   dipin   26.0  sreenath     24
2  103     joe   27.0   sreerag     27
3  105     NaN    NaN   shafeel     26

##Pivot and Pivot tables
Pivot allows to reshape the data frame

pivot table is used to summarize or aggregate data with in a dataframe

In [ ]:
import pandas as pd
datas=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dataset/weather_dataset.csv')
datas

,Date,City,Temperature,Humidity,Wind Speed (km/h),Weather Condition
0,2025-08-01,Mumbai,30,85,12,Rainy
1,2025-08-01,Delhi,36,40,18,Sunny
2,2025-08-01,Bengaluru,27,70,10,Cloudy
3,2025-08-02,Mumbai,29,88,14,Rainy
4,2025-08-02,Delhi,35,45,20,Sunny
5,2025-08-02,Bengaluru,26,72,9,Cloudy
6,2025-08-03,Mumbai,28,90,11,Rainy
7,2025-08-03,Delhi,34,50,22,Partly Cloudy
8,2025-08-03,Bengaluru,27,68,8,Cloudy

create a table with date as index and city as columns

In [ ]:
datas.pivot(index='Date',columns='City')

           Temperature               Humidity              Wind Speed (km/h)  \
City         Bengaluru Delhi Mumbai Bengaluru Delhi Mumbai         Bengaluru
Date
2025-08-01          27    36     30        70    40     85                10
2025-08-02          26    35     29        72    45     88                 9
2025-08-03          27    34     28        68    50     90                 8

                        Weather Condition
City       Delhi Mumbai         Bengaluru          Delhi Mumbai
Date
2025-08-01    18     12            Cloudy          Sunny  Rainy
2025-08-02    20     14            Cloudy          Sunny  Rainy
2025-08-03    22     11            Cloudy  Partly Cloudy  Rainy

create a table with Temperature

In [ ]:
datas.pivot(index='Date',columns='City',values='Temperature')

City        Bengaluru  Delhi  Mumbai
Date
2025-08-01         27     36      30
2025-08-02         26     35      29
2025-08-03         27     34      28

used to summarize or aggregate data with in a dataframetas.pivot_table(index='City',columns='Date' ,aggfunc='sum')

In [ ]:
datas.pivot_table(index='City',columns='Date',aggfunc='sum',margins=True)

            Humidity                            Temperature             \
Date      2025-08-01 2025-08-02 2025-08-03  All  2025-08-01 2025-08-02
City
Bengaluru         70         72         68  210          27         26
Delhi             40         45         50  135          36         35
Mumbai            85         88         90  263          30         29
All              195        205        208  608          93         90

                          Weather Condition                    \
Date      2025-08-03  All        2025-08-01        2025-08-02
City
Bengaluru         27   80            Cloudy            Cloudy
Delhi             34  105             Sunny             Sunny
Mumbai            28   87             Rainy             Rainy
All               89  272  RainySunnyCloudy  RainySunnyCloudy

                                     \
Date                     2025-08-03
City
Bengaluru                    Cloudy
Delhi                 Partly Cloudy
Mumbai                        Rainy
All        RainyPartly CloudyCloudy

                                                              \
Date                                                     All
City
Bengaluru                                 CloudyCloudyCloudy
Delhi                                SunnySunnyPartly Cloudy
Mumbai                                       RainyRainyRainy
All        RainySunnyCloudyRainySunnyCloudyRainyPartly Cl...

          Wind Speed (km/h)
Date             2025-08-01 2025-08-02 2025-08-03  All
City
Bengaluru                10          9          8   27
Delhi                    18         20         22   60
Mumbai                   12         14         11   37
All                      40         43         41  124

###Pivot Grouper

In [ ]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dataset/Sales_data.csv')

df

   OrderID        Date     Category     Product  Quantity  Price
0     1001  2023-01-15  Electronics      Laptop         2  70000
1     1002  2023-01-20    Furniture       Chair         4   1500
2     1003  2023-02-05  Electronics  Headphones         5   2000
3     1004  2023-02-18    Furniture       Table         1   5000
4     1005  2023-03-03   Stationery    Notebook        10     50
5     1006  2023-03-25  Electronics       Mouse         6    800
6     1007  2023-04-10    Furniture        Sofa         1  15000
7     1008  2023-04-15   Stationery         Pen        20     20
8     1009  2023-05-01  Electronics      Laptop         1  70000
9     1010  2023-05-12    Furniture       Chair         2   1500

add total sales column

In [ ]:
df['Total']=df['Quantity']*df['Price']
df

   OrderID        Date     Category     Product  Quantity  Price   Total
0     1001  2023-01-15  Electronics      Laptop         2  70000  140000
1     1002  2023-01-20    Furniture       Chair         4   1500    6000
2     1003  2023-02-05  Electronics  Headphones         5   2000   10000
3     1004  2023-02-18    Furniture       Table         1   5000    5000
4     1005  2023-03-03   Stationery    Notebook        10     50     500
5     1006  2023-03-25  Electronics       Mouse         6    800    4800
6     1007  2023-04-10    Furniture        Sofa         1  15000   15000
7     1008  2023-04-15   Stationery         Pen        20     20     400
8     1009  2023-05-01  Electronics      Laptop         1  70000   70000
9     1010  2023-05-12    Furniture       Chair         2   1500    3000

create pivot table with grouper(monthly)

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])
pivot =pd.pivot_table(df,
    index=pd.Grouper(key='Date',freq='ME'),
    columns='Category',
    values='Total',
    aggfunc='sum')
pivot

Category    Electronics  Furniture  Stationery
Date
2023-01-31     140000.0     6000.0         NaN
2023-02-28      10000.0     5000.0         NaN
2023-03-31       4800.0        NaN       500.0
2023-04-30          NaN    15000.0       400.0
2023-05-31      70000.0     3000.0         NaN

##Melt

Melt allows to transform or reshape the data frame.

In [ ]:
import pandas as pd
datas=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dataset/weather_dataset.csv')
datas

,Date,City,Temperature,Humidity,Wind Speed (km/h),Weather Condition
0,2025-08-01,Mumbai,30,85,12,Rainy
1,2025-08-01,Delhi,36,40,18,Sunny
2,2025-08-01,Bengaluru,27,70,10,Cloudy
3,2025-08-02,Mumbai,29,88,14,Rainy
4,2025-08-02,Delhi,35,45,20,Sunny
5,2025-08-02,Bengaluru,26,72,9,Cloudy
6,2025-08-03,Mumbai,28,90,11,Rainy
7,2025-08-03,Delhi,34,50,22,Partly Cloudy
8,2025-08-03,Bengaluru,27,68,8,Cloudy

In [ ]:
pd.melt(datas,id_vars=['Date'])

          Date           variable          value
0   2025-08-01               City         Mumbai
1   2025-08-01               City          Delhi
2   2025-08-01               City      Bengaluru
3   2025-08-02               City         Mumbai
4   2025-08-02               City          Delhi
5   2025-08-02               City      Bengaluru
6   2025-08-03               City         Mumbai
7   2025-08-03               City          Delhi
8   2025-08-03               City      Bengaluru
9   2025-08-01        Temperature             30
10  2025-08-01        Temperature             36
11  2025-08-01        Temperature             27
12  2025-08-02        Temperature             29
13  2025-08-02        Temperature             35
14  2025-08-02        Temperature             26
15  2025-08-03        Temperature             28
16  2025-08-03        Temperature             34
17  2025-08-03        Temperature             27
18  2025-08-01           Humidity             85
19  2025-08-01           Humidity             40
20  2025-08-01           Humidity             70
21  2025-08-02           Humidity             88
22  2025-08-02           Humidity             45
23  2025-08-02           Humidity             72
24  2025-08-03           Humidity             90
25  2025-08-03           Humidity             50
26  2025-08-03           Humidity             68
27  2025-08-01  Wind Speed (km/h)             12
28  2025-08-01  Wind Speed (km/h)             18
29  2025-08-01  Wind Speed (km/h)             10
30  2025-08-02  Wind Speed (km/h)             14
31  2025-08-02  Wind Speed (km/h)             20
32  2025-08-02  Wind Speed (km/h)              9
33  2025-08-03  Wind Speed (km/h)             11
34  2025-08-03  Wind Speed (km/h)             22
35  2025-08-03  Wind Speed (km/h)              8
36  2025-08-01  Weather Condition          Rainy
37  2025-08-01  Weather Condition          Sunny
38  2025-08-01  Weather Condition         Cloudy
39  2025-08-02  Weather Condition          Rainy
40  2025-08-02  Weather Condition          Sunny
41  2025-08-02  Weather Condition         Cloudy
42  2025-08-03  Weather Condition          Rainy
43  2025-08-03  Weather Condition  Partly Cloudy
44  2025-08-03  Weather Condition         Cloudy

In [ ]:
melted=pd.melt(datas,
               id_vars=['City','Date','Weather Condition'],
               value_vars=['Temperature','Humidity'],
               var_name='Weather_Parameter',
               value_name='Reading')
melted

         City        Date Weather Condition Weather_Parameter  Reading
0      Mumbai  2025-08-01             Rainy       Temperature       30
1       Delhi  2025-08-01             Sunny       Temperature       36
2   Bengaluru  2025-08-01            Cloudy       Temperature       27
3      Mumbai  2025-08-02             Rainy       Temperature       29
4       Delhi  2025-08-02             Sunny       Temperature       35
5   Bengaluru  2025-08-02            Cloudy       Temperature       26
6      Mumbai  2025-08-03             Rainy       Temperature       28
7       Delhi  2025-08-03     Partly Cloudy       Temperature       34
8   Bengaluru  2025-08-03            Cloudy       Temperature       27
9      Mumbai  2025-08-01             Rainy          Humidity       85
10      Delhi  2025-08-01             Sunny          Humidity       40
11  Bengaluru  2025-08-01            Cloudy          Humidity       70
12     Mumbai  2025-08-02             Rainy          Humidity       88
13      Delhi  2025-08-02             Sunny          Humidity       45
14  Bengaluru  2025-08-02            Cloudy          Humidity       72
15     Mumbai  2025-08-03             Rainy          Humidity       90
16      Delhi  2025-08-03     Partly Cloudy          Humidity       50
17  Bengaluru  2025-08-03            Cloudy          Humidity       68

##Cross tab or contingency table

In pandas, pd.crosstab() is used to compute a cross-tabulation of two or more factors. It’s often used for analyzing categorical variables, similar to a contingency table in statistics.

syntax:

pd.crosstab(index, columns, values=None, aggfunc=None, margins=False, margins_name='All')

In [ ]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dataset/survey_crosstab.csv')
df

   RespondentID  Gender AgeGroup Preferred_Device
0             1    Male    18-25           Laptop
1             2  Female    26-35           Mobile
2             3    Male    18-25           Tablet
3             4  Female    18-25           Mobile
4             5    Male    26-35           Laptop
5             6  Female    18-25           Mobile
6             7    Male    36-45           Laptop
7             8  Female    26-35           Tablet
8             9    Male    26-35           Mobile
9            10  Female    36-45           Laptop

create cross_tabulation

In [ ]:
ct=pd.crosstab(df['Gender'],df['Preferred_Device'])
print(ct)

Preferred_Device  Laptop  Mobile  Tablet
Gender
Female                 1       3       1
Male                   3       1       1

Cross-tab of AgeGroup vs Preferred_Device with totals:

In [ ]:
ct2=pd.crosstab(df['AgeGroup'],df['Preferred_Device'],margins=True,margins_name='Total')
print(ct2)

Preferred_Device  Laptop  Mobile  Tablet  Total
AgeGroup
18-25                  1       2       1      4
26-35                  1       2       1      4
36-45                  2       0       0      2
Total                  4       4       2     10

##to_datetime()

to_datetime function is very useful in pandas to convert any string date to type datetime

In [ ]:
import pandas as pd
pd.to_datetime(['05/01/2017'],dayfirst=True)

DatetimeIndex(['2017-01-05'], dtype='datetime64[ns]', freq=None)

In [ ]:
dates=['2023-01-01','invalid_date','2023-03-30']
pd.to_datetime(dates,errors='coerce')

DatetimeIndex(['2023-01-01', 'NaT', '2023-03-30'], dtype='datetime64[ns]', freq=None)

In [ ]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dataset/weather_dataset.csv')
df

,Date,City,Temperature,Humidity,Wind Speed (km/h),Weather Condition
0,2025-08-01,Mumbai,30,85,12,Rainy
1,2025-08-01,Delhi,36,40,18,Sunny
2,2025-08-01,Bengaluru,27,70,10,Cloudy
3,2025-08-02,Mumbai,29,88,14,Rainy
4,2025-08-02,Delhi,35,45,20,Sunny
5,2025-08-02,Bengaluru,26,72,9,Cloudy
6,2025-08-03,Mumbai,28,90,11,Rainy
7,2025-08-03,Delhi,34,50,22,Partly Cloudy
8,2025-08-03,Bengaluru,27,68,8,Cloudy

**Applymap**

 Use applymap() to increase all numeric values by 1.0 (if applicable)

We must exclude the 'City' column (non-numeric), or handle non-numeric safely

In [ ]:
print('original Dataframe:')
print(df)
df_numeric=df.select_dtypes(include='number')
df[df_numeric.columns]=df_numeric.applymap(lambda x:  x + 1)
print('\ndataframe after applymap(numeric values+1):')
df

original Dataframe:
         Date       City  Temperature  Humidity  Wind Speed (km/h)  \
0  2025-08-01     Mumbai           33        88                 15
1  2025-08-01      Delhi           39        43                 21
2  2025-08-01  Bengaluru           30        73                 13
3  2025-08-02     Mumbai           32        91                 17
4  2025-08-02      Delhi           38        48                 23
5  2025-08-02  Bengaluru           29        75                 12
6  2025-08-03     Mumbai           31        93                 14
7  2025-08-03      Delhi           37        53                 25
8  2025-08-03  Bengaluru           30        71                 11

  Weather Condition
0             Rainy
1             Sunny
2            Cloudy
3             Rainy
4             Sunny
5            Cloudy
6             Rainy
7     Partly Cloudy
8            Cloudy

dataframe after applymap(numeric values+1):

/tmp/ipython-input-3594783373.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[df_numeric.columns]=df_numeric.applymap(lambda x:  x + 1)

,Date,City,Temperature,Humidity,Wind Speed (km/h),Weather Condition
0,2025-08-01,Mumbai,34,89,16,Rainy
1,2025-08-01,Delhi,40,44,22,Sunny
2,2025-08-01,Bengaluru,31,74,14,Cloudy
3,2025-08-02,Mumbai,33,92,18,Rainy
4,2025-08-02,Delhi,39,49,24,Sunny
5,2025-08-02,Bengaluru,30,76,13,Cloudy
6,2025-08-03,Mumbai,32,94,15,Rainy
7,2025-08-03,Delhi,38,54,26,Partly Cloudy
8,2025-08-03,Bengaluru,31,72,12,Cloudy